### ISSUE TITLE
How to identify whether a single sample is in distribution or not?

### ISSUE THREAD

**Issue by lingjunz** [engkarat/cosine-ood-detector#1]
It seems that we can distinguish the in-distribution datasets and OOD datasets with AUROC & AUPR successfully using the proposed method. 

But how can we identify whether a single sample is in the distribution or not?

Is it still a threshold-based method that we should set a threshold to deliver it?

Thanks for your kindly response.

**Comment by engkarat** [comment]
Thank you for your message.

Yes, it is. In this field of research, we aim to study properties of neural network that encourage differentiable of in and out-of-distribution. But as you mentioned, it turns out that eventually one needs to set threshold up for the detection in real-world deployment system.
